"""Build 30 technical deep-dive cards from the opportunity pool and local evidence."""

from __future__ import annotations

import json
import sys
from datetime import date
from pathlib import Path


ROOT = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(r"D:\Repository\ReadPaper\daily\20260826_后处理调研")
OUT = ROOT / "metadata" / "deep_dive_30.jsonl"
NOTE = ROOT / "notes" / "deep_dive_30.md"
OPPORTUNITIES = ROOT / "metadata" / "opportunities.jsonl"

CARDS = [
    {
        "op_id": "OP-001", "title": "动态星芒与镜头眩光视频化", "english": "Temporal starburst and lens-flare rendering", "family": "computational_optics",
        "mode": "online_recording", "truth": "perceptual", "source_ids": ["official_apple_cinematic_mode", "local_fluxir"],
        "problem": "逐帧叠加星芒/flare 会出现亮度跳变、光源形状游走和镜头运动不一致。",
        "solution": "先检测高亮光源，再用光源轨迹、相机姿态和参数化 PSF 生成 flare；将光源 ID、中心、强度和遮挡状态写入 temporal state。",
        "inputs": "YUV/RGB + 连续帧 + IMU/电子防抖运动 + 高亮点 mask；可选深度。",
        "model": "轻量高亮检测器 + 光源 tracking + 参数化渲染器；生成式版本可用 latent adapter，但不应作为第一版在线链路。",
        "training": "真实夜景/舞台视频；合成多种光圈、鬼影和星芒参数；加入不同曝光、镜头污渍和 rolling-shutter 扰动。",
        "loss": "L = L_render_recon + 0.2 L_temporal_warp + 0.1 L_highlight_shape + 0.05 L_flicker；权重为起始假设，必须做梯度与消融。",
        "temporal": "光源 track + EMA 强度 + 关键帧重新估计；遮挡或镜头切换时重置。",
        "edge": "预览低分辨率分析，录制时只对光源 ROI 渲染；4K 录后再做高质量 flare。",
        "risks": "把真实光学缺陷变成错误内容；flare 过强会遮挡主体；不同镜头的光学风格难以统一。",
        "mvp": "先实现 1-3 个高亮点、2 种星芒形状、固定参数化鬼影，并验证 30fps 预览稳定性。",
    },
    {
        "op_id": "OP-009", "title": "人像主光与轮廓光重定向", "english": "Portrait key-light and rim-light steering", "family": "relighting",
        "mode": "offline_device", "truth": "generative", "source_ids": ["local_fluxir", "local_authface", "official_capcut_video_cutout"],
        "problem": "拍摄时光线不可控；静态 relighting 迁移到录像会产生脸部颜色和阴影闪烁。",
        "solution": "以 face/body parsing、法线或 3D face proxy 估计可解释的 light field，再使用条件生成器重建局部光照；只在 mask 内生成，背景使用保守颜色匹配。",
        "inputs": "连续 RGB/YUV + face/body mask + landmark + 可选深度/IMU。",
        "model": "轻量 intrinsic decomposition + temporal U-Net/DiT adapter；高质量录后可接 FLUX/扩散教师模型蒸馏。",
        "training": "HDR 人像、多光源人像、真实手机视频；用光照可控 3D 人脸和渲染数据补充主光方向、颜色、强度标签。",
        "loss": "重建 L1/Charbonnier + ROI perceptual + identity cosine + temporal warp + boundary alpha + illumination smoothness；身份损失只作用于脸部高层 embedding。",
        "temporal": "关键帧估计 light code，帧间用光流/track 传播；表情或大姿态变化触发局部重估。",
        "edge": "实时预览只给低频亮度变化；录后做细节和阴影生成。必须保留原片和 relight mask。",
        "risks": "改变肤色、五官或身份；头发和眼镜边界泄漏；不同人的皮肤反射模型差异大。",
        "mvp": "只做正面单人、主光左右移动、三档强度，先验证肤色稳定和身份相似度。",
    },
    {
        "op_id": "OP-017", "title": "录后改光圈与时序景深", "english": "Post-capture aperture and temporal depth-of-field", "family": "depth_focus",
        "mode": "offline_device", "truth": "perceptual", "source_ids": ["official_google_cinematic_blur", "local_fluxsr", "local_tiger"],
        "problem": "视频虚化比单帧更容易出现头发抖动、边缘漏背景和深度跳变。",
        "solution": "用时序 depth + segmentation + motion boundary refinement 生成 blur field；对前景边界采用多层 alpha 和不确定性融合。",
        "inputs": "连续 RGB + depth/dual-camera disparity + person/scene mask + optical flow。",
        "model": "轻量深度网络 + recurrent refinement + differentiable defocus renderer。",
        "training": "真实双摄/多摄视频、带深度相机数据、电影镜头数据；合成不同 aperture、focus distance 和运动模糊。",
        "loss": "深度 L1 + alpha boundary + perceptual + temporal consistency + blur-kernel regularization；对发丝设置高权重边界采样。",
        "temporal": "深度低频状态保持，运动边界局部更新；长遮挡后回到关键帧重估。",
        "edge": "预览只显示粗粒度虚化；录后 1080p/4K 做高质量 alpha refinement。",
        "risks": "深度错层导致人脸/头发被切断；生成 blur 改变真实空间关系；低照度深度不可靠。",
        "mvp": "单人半身、背景相对静止、三档 aperture；用 flicker rate 和 hair-boundary IoU 做核心指标。",
    },
    {
        "op_id": "OP-025", "title": "语义长曝光与主体保持清晰", "english": "Semantic long exposure with sharp subjects", "family": "temporal_exposure",
        "mode": "offline_device", "truth": "generative", "source_ids": ["local_flashvsr", "local_wfvae"],
        "problem": "传统长曝光视频会同时拖糊主体；简单帧叠加不能处理遮挡与非刚性运动。",
        "solution": "分离 camera motion、background motion、subject motion，对不同区域使用不同时间积分；用视频 latent/warp 保留主体纹理。",
        "inputs": "连续帧 + optical flow + IMU + subject mask + optional depth。",
        "model": "motion decomposition + feature propagation + semantic compositor；录后可使用视频扩散/flow model 做局部补全。",
        "training": "真实短曝光序列合成长曝光目标；真实车流、瀑布、舞蹈和光轨视频；加入遮挡与曝光变化。",
        "loss": "区域重建 + motion-streak prior + temporal warp + subject identity/edge loss + background smoothness。",
        "temporal": "以参考帧作为主体锚点，背景轨迹可累计；主体出入画面时切换 track state。",
        "edge": "不建议实时全画面；在线只保存 ring buffer 和运动场，录后生成。",
        "risks": "背景运动和主体运动分离失败；生成轨迹不符合真实物理；大幅运动造成 ghosting。",
        "mvp": "固定机位车流和单人挥手两个场景，分别测主体清晰度、拖影连续性和用户偏好。",
    },
    {
        "op_id": "OP-033", "title": "高分辨率采集驱动的数字滑轨", "english": "High-resolution capture for digital dolly", "family": "virtual_camera",
        "mode": "offline_device", "truth": "generative", "source_ids": ["local_fluxsr", "local_fluxir", "local_dit"],
        "problem": "手机数字运镜受裁切、视角变化和画外区域限制；单纯缩放没有真实视差。",
        "solution": "以高分辨率采集、深度/语义层和相机轨迹估计生成有限视差；超出可见区域部分使用内容延展，并标记生成区域。",
        "inputs": "高分辨率视频 + depth/多摄 + IMU + semantic layers。",
        "model": "depth-aware image warping + hole filling + optional neural rendering/FLUX adapter。",
        "training": "多摄/多视角视频、室内外静态场景和缓慢运动视频；合成相机轨迹、孔洞和视差变化。",
        "loss": "多视角 photometric + depth consistency + perceptual + hole-boundary + trajectory smoothness。",
        "temporal": "相机轨迹全局平滑，场景层局部跟踪；每次大幅改变机位时以 keyframe 重新生成。",
        "edge": "实时只预览 crop/warp；录后做高质量 outpainting。",
        "risks": "画外区域幻觉；平面假设导致几何撕裂；人物和细节容易身份漂移。",
        "mvp": "室内产品和单人静态场景，限制轨迹为水平滑轨和轻微 push-in。",
    },
    {
        "op_id": "OP-041", "title": "无感切镜与跨摄像头颜色连续", "english": "Seamless lens switching with color continuity", "family": "multi_camera",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["official_apple_cinematic_mode", "official_blackmagic_gen5_color", "official_samsung_super_steady"],
        "problem": "手机多摄切换时曝光、AWB、噪声、锐度、视场和运动状态会突然变化。",
        "solution": "提前 warm-up 辅摄状态，建立每颗镜头的 color/noise/sharpness transform，并共享 IMU、AF、AE 和 temporal feature state。",
        "inputs": "多摄 RAW/YUV + IMU + AE/AWB/AF state + lens metadata。",
        "model": "跨摄像头对齐 + online color transform + feature/state handoff；不依赖生成模型。",
        "training": "同步多摄视频，覆盖不同光照和焦段；采集镜头 response、噪声和畸变标定数据。",
        "loss": "跨摄颜色差异 + tone continuity + temporal flow + edge sharpness consistency + switch transient penalty。",
        "temporal": "切换前 N 帧并行估计，切换后共享参考帧；镜头状态机控制 reset。",
        "edge": "ISP/视频管线前端优先落地，适合 30/60fps 实时。",
        "risks": "不同传感器动态范围差异无法完全补偿；切换时视差和 AF 状态仍可能突变。",
        "mvp": "主摄/长焦两路，固定三档变焦切换；指标为 switch transient、肤色差和用户可见跳变率。",
    },
    {
        "op_id": "OP-049", "title": "相机运动与主体运动解耦稳定", "english": "Camera-motion and subject-motion disentangled stabilization", "family": "motion_quality",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["official_gopro_hypersmooth", "official_dji_rocksteady", "local_flashvsr"],
        "problem": "全局 EIS 会把主体运动当成相机抖动，导致人体形变、背景冻结或运动意图消失。",
        "solution": "联合 IMU、global camera pose、optical flow 和 semantic tracks，分离刚性相机运动与非刚性主体运动。",
        "inputs": "YUV/RGB + IMU + EIS gyro + subject masks + optical flow。",
        "model": "causal motion decomposition network + mesh/flow warper。",
        "training": "真实运动视频与 IMU、合成抖动轨迹、人体/车辆运动数据；加入 rolling shutter 和遮挡。",
        "loss": "camera reprojection + non-rigid flow smoothness + subject shape preservation + horizon/line stability + temporal consistency。",
        "temporal": "低频相机轨迹使用长窗口，主体轨迹使用短窗口；快速转身或遮挡时局部 reset。",
        "edge": "可放在 EIS 后端/编码前，先低分辨率估计高分辨率 warp。",
        "risks": "场景多主体和透明物体难以分解；运动语义判断错误会造成不自然稳定。",
        "mvp": "跑步、骑行、手持走路三场景，比较普通 EIS 与 intent-aware EIS 的主观自然度。",
    },
    {
        "op_id": "OP-057", "title": "视频夜视与高光保护联合", "english": "Video night enhancement with highlight protection", "family": "night_hdr",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["official_google_video_boost", "local_flashvsr", "local_wfvae"],
        "problem": "夜景视频同时面临暗部噪声、运动模糊、霓虹高光和曝光呼吸，单帧增强会放大闪烁。",
        "solution": "联合多帧对齐、曝光状态、语义高光 mask 和时序降噪；暗部/高光使用不同的 restoration policy。",
        "inputs": "RAW/YUV 多帧 + AE metadata + motion + highlight mask + optional multi-exposure。",
        "model": "causal VRT-like transformer / recurrent restoration；高质量模式可用 latent diffusion teacher 蒸馏。",
        "training": "真实夜景视频、短曝光到长曝光配对、合成 sensor noise/ISO/色偏/高光裁切；保留真实 motion。",
        "loss": "Charbonnier + perceptual + temporal warp + chroma noise + highlight roll-off + exposure trajectory loss。",
        "temporal": "低频颜色与亮度状态记忆，高频细节使用短时参考；高光区禁止跨帧平均过度。",
        "edge": "预览 720p/1080p 轻量模式；录后旗舰模式用更长参考队列。",
        "risks": "夜景生成纹理不真实；灯牌/车灯被错误抹除；高 ISO 真实细节不可恢复。",
        "mvp": "城市夜景、室内移动、逆光人像三组，重点看 flicker、highlight clipping 和肤色。",
    },
    {
        "op_id": "OP-065", "title": "视频人像分区恢复与身份锚定", "english": "Region-aware portrait restoration with identity anchoring", "family": "portrait_identity",
        "mode": "online_recording", "truth": "perceptual", "source_ids": ["local_tiger", "local_svfr", "local_authface"],
        "problem": "统一人像美化会把脸、头发、眼睛、牙齿和衣服用同一策略处理，导致身份漂移和局部过度锐化。",
        "solution": "使用 face parsing/landmarks/track ID 建立区域化处理；以 identity embedding 锚定五官结构，用 temporal ROI features 保持连续。",
        "inputs": "YUV/RGB + face/body parsing + landmarks + track ID + optional reference frame。",
        "model": "ROI transformer/recurrent restoration + identity branch + mask-conditioned decoder。",
        "training": "真实人像视频、VFH​​Q/CelebV-HQ/FFHQ 类静态数据、合成压缩/模糊/噪声/遮挡；加入不同年龄、肤色、妆容。",
        "loss": "区域重建 + ROI perceptual + ArcFace/identity cosine + temporal feature consistency + mask boundary + skin-color stability。",
        "temporal": "每个 track 维护 identity prototype；关键帧更新 prototype，普通帧只更新局部特征。",
        "edge": "脸部 ROI 低分辨率分析、高分辨率局部增强；多人时按重要性预算。",
        "risks": "身份 loss 过强会压制真实表情；过度生成会改变年龄/五官；mask 错误会伤及头发和背景。",
        "mvp": "单人近景、30fps、脸部五分区，先验证身份余弦、纹理稳定和用户偏好。",
    },
    {
        "op_id": "OP-073", "title": "视频路人和电线时序移除", "english": "Temporal passerby and wire removal", "family": "scene_editing",
        "mode": "offline_device", "truth": "generative", "source_ids": ["official_adobe_content_aware_fill_video", "official_davinci_object_removal", "official_davinci_magic_mask"],
        "problem": "视频移除不是单帧 inpainting：需要处理动态背景、遮挡关系、镜头运动和新出现区域。",
        "solution": "对象 tracking -> 背景板/时空 memory -> motion-compensated fill -> boundary refinement；输出移除 mask 和可回退原片。",
        "inputs": "连续视频 + object mask + camera motion + depth/scene segmentation。",
        "model": "video inpainting transformer；高质量模式可使用扩散/DiT 的局部条件编辑。",
        "training": "DAVIS/YouTube-VOS 类视频 mask、真实路人/电线采集、合成对象插入和镜头运动；对背景动态单独采样。",
        "loss": "known-region reconstruction + hole perceptual + temporal warp + boundary gradient + object-removal consistency。",
        "temporal": "用稳定背景 memory 作为参考，背景变化时更新；长时间遮挡需要生成式重建并降低置信度。",
        "edge": "适合录后端侧；实时只做检测、预览 mask 和短时移除。",
        "risks": "背景板不真实、重复纹理、人物边界残留；生成区域可能改变事实。",
        "mvp": "固定机位路人移除和电线移除，约束对象不超过 2 个，输出可回退的编辑工程。",
    },
    {
        "op_id": "OP-081", "title": "语义分区 LUT 与动态胶片质感", "english": "Semantic local LUT and dynamic film look", "family": "color_science",
        "mode": "online_recording", "truth": "perceptual", "source_ids": ["official_panasonic_real_time_lut", "official_blackmagic_gen5_color", "official_sony_s_cinetone"],
        "problem": "全局 LUT 会同时改变肤色、天空、霓虹和阴影；颗粒和晕光逐帧生成会闪烁。",
        "solution": "按语义区域使用局部 color transform；颗粒、halation、tone curve 与亮度、ISO、运动状态绑定并用状态滤波稳定。",
        "inputs": "YUV/Log + scene segmentation + exposure/ISO metadata + motion state。",
        "model": "轻量 semantic segmentation + 3D LUT/MLP color transform + procedural grain/halation renderer。",
        "training": "多相机、多光照、参考电影片段；采集颜色 chart、肤色和不同 ISO 的颗粒统计。",
        "loss": "色彩重建 + skin-tone deviation + look perceptual + temporal color stability + grain spectrum matching。",
        "temporal": "LUT 参数低通，区域 mask 采用 tracking；镜头切换时使用颜色状态 handoff。",
        "edge": "适合实时录像，核心工作放在 ISP/GPU；高质量纹理可录后叠加。",
        "risks": "语义分割错会导致局部颜色断层；风格与真实颜色边界模糊；不同屏幕显示不一致。",
        "mvp": "肤色/天空/高亮三类区域 + 两种 film look，比较全局 LUT 与语义 LUT 的用户偏好。",
    },
    {
        "op_id": "OP-089", "title": "说话人驱动构图、跟焦和变焦", "english": "Speaker-driven framing, focus, and zoom", "family": "audio_visual",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["official_blackmagic_camera_app", "official_sony_real_time_tracking", "official_insta360_me_mode"],
        "problem": "采访/直播中相机不知道谁在说话，单纯人脸 tracking 会在多人之间错误切换。",
        "solution": "音频 DOA/ASR/说话人 diarization 与 face track 对齐，再用 shot policy 控制景别、焦点和数字 crop。",
        "inputs": "多麦克风音频 + face tracks + body pose + camera metadata。",
        "model": "低延迟 audio-visual association + policy/state machine；避免直接使用大模型在线决策。",
        "training": "多说话人采访、播客、会议和嘈杂环境；标注说话人-脸对应、镜头选择和用户偏好。",
        "loss": "speaker-face matching + focus/framing classification + trajectory smoothness + shot-switch penalty。",
        "temporal": "说话人状态需有 hysteresis；至少持续若干帧才切换镜头，停顿时保留上一状态。",
        "edge": "DSP 运行声源特征，NPU 运行脸部 track，策略在 CPU/轻量 runtime；可 30fps 在线。",
        "risks": "多人抢话、遮挡和混响会造成错配；自动运镜可能让用户失去控制。",
        "mvp": "双人采访，只有 wide/medium 两种景别和一个焦点策略，加入手动锁定优先级。",
    },
    {
        "op_id": "OP-097", "title": "有限视角扩展与视频画外补全", "english": "Constrained novel-view extension and video outpainting", "family": "generative_video",
        "mode": "offline_device", "truth": "generative", "source_ids": ["local_fluxir", "local_fluxsr", "local_dit", "local_magvit"],
        "problem": "横竖屏裁切、数字运镜和镜头延展需要画外内容，但逐帧生成会出现结构和纹理漂移。",
        "solution": "使用 depth/scene layout/trajectory 约束时空 outpainting；以关键帧生成画外结构，再用视频 latent/feature propagation 传播。",
        "inputs": "视频 + camera trajectory + depth/segmentation + text/reference optional。",
        "model": "video VAE/DiT latent editor + spatial adapter + temporal attention；端侧只考虑短片段录后。",
        "training": "多视角/宽幅视频裁切任务、合成画外区域、动态对象和遮挡；使用区域 mask 作为 supervision。",
        "loss": "known-region identity + generated-region perceptual + temporal consistency + layout/depth consistency + boundary blend。",
        "temporal": "只对新增区域生成；原视频区域尽量 copy/warp，关键帧负责结构锚定。",
        "edge": "优先云端或旗舰录后；手机端可限制输出边界和长度。",
        "risks": "画外事实不可验证；人物、文字、建筑结构容易幻觉；用户可能误以为是原始录像。",
        "mvp": "横转竖/竖转横 + 10% 边界延展，仅静态背景和短片段，保留生成 mask。",
    },
    {
        "op_id": "OP-105", "title": "录制代理与录后高质量重算", "english": "Proxy capture with post-capture quality rerender", "family": "capture_assistance",
        "mode": "offline_device", "truth": "faithful", "source_ids": ["official_google_video_boost", "local_flashvsr", "local_wfvae"],
        "problem": "高质量算法无法在所有手机、温度和录像时长下实时运行，但只保存压缩视频又失去后处理所需信息。",
        "solution": "录像时保存轻量 proxy、关键帧、深度/mask/IMU/曝光状态和压缩 latent；停止录像后按设备预算重算。",
        "inputs": "原始/高质量 proxy + metadata + motion/depth/mask + optional encoded latent。",
        "model": "在线轻量模型 + 录后 VRT/flow/diffusion/FLUX adapter；可按温度动态选择。",
        "training": "从同一段真实视频产生不同 proxy 和高质量目标；覆盖中断、掉帧、温度降级和存储受限。",
        "loss": "proxy-to-GT restoration + metadata consistency + temporal quality + rate/storage regularization。",
        "temporal": "完整时序状态保存在片段级 manifest；录后允许双向模型，在线只需因果状态。",
        "edge": "最适合把前沿模型带入手机，但需要存储、后台任务和用户等待交互。",
        "risks": "存储成本、后台耗电、任务中断和用户对最终结果等待时间的接受度。",
        "mvp": "1080p/10秒片段，保存低码率 proxy + motion/mask metadata，比较录后重算与实时输出。",
    },
    {
        "op_id": "OP-003", "title": "镜头污渍、雨滴与玻璃反射抑制", "english": "Lens contamination and reflection suppression", "family": "computational_optics",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["official_davinci_magic_mask", "official_adobe_roto_brush", "local_fluxir"],
        "problem": "镜头雨滴、污渍和玻璃反射会在视频中产生固定/移动遮挡，单帧修复容易产生背景复制和闪烁。",
        "solution": "识别 contamination type，利用相机运动、背景记忆和 reflection/transmission separation 做保守抑制；低置信度区域保持原片。",
        "inputs": "连续帧 + lens contamination mask + camera motion + depth/scene segmentation。",
        "model": "污染检测 + background memory + video inpainting/reflectance separation。",
        "training": "真实雨滴/玻璃拍摄、可控喷雾和污渍数据、合成反射/透射层；保留透明和半透明边界。",
        "loss": "mask-aware reconstruction + temporal warp + transparency consistency + background edge loss。",
        "temporal": "固定污渍用长期背景参考，移动雨滴用短期 track；镜头移动时更新 reference。",
        "edge": "检测可实时，强修复适合录后；保留“原片/抑制版”双输出。",
        "risks": "真实高光被误判为污渍；透明物体的真实性难以恢复；背景运动时生成失败。",
        "mvp": "固定镜头污渍和车窗反射两个场景，输出置信度和回退开关。",
    },
    {
        "op_id": "OP-011", "title": "多人独立打光与共享环境光", "english": "Independent multi-person relighting with shared environment light", "family": "relighting",
        "mode": "offline_device", "truth": "generative", "source_ids": ["local_fluxir", "local_authface", "official_capcut_video_cutout"],
        "problem": "多人画面中每个人的肤色、朝向和遮挡不同，统一打光会产生不自然的阴影与颜色。",
        "solution": "按 track ID 估计每人局部 light code，同时共享一个环境光低频场；遮挡关系决定前后景合成顺序。",
        "inputs": "multi-person tracks + parsing masks + pose/normal proxy + scene segmentation。",
        "model": "multi-ROI relighting network + shared environment latent + compositing module。",
        "training": "多人 HDR 人像、真实补光视频、3D human relighting 数据；合成不同人数和遮挡关系。",
        "loss": "person ROI reconstruction + identity + inter-person color consistency + occlusion boundary + temporal track consistency。",
        "temporal": "每个 track 独立维护 light state，环境光使用全局低频状态；新人出现时 warm-up。",
        "edge": "多人数量和 ROI 面积决定预算；实时预览只做两人以内，录后支持更多人。",
        "risks": "身份/肤色不一致、人物边界互相污染、生成阴影不符合场景。",
        "mvp": "双人正面站立，单一环境光、左右主光两档，先测色彩一致和边界。",
    },
    {
        "op_id": "OP-019", "title": "语义分层虚拟移轴", "english": "Semantic layered virtual tilt-shift", "family": "depth_focus",
        "mode": "offline_device", "truth": "perceptual", "source_ids": ["official_google_cinematic_blur", "local_fluxsr"],
        "problem": "移轴效果需要倾斜焦平面，普通手机没有足够光学自由度，视频中还需处理相机运动和多层深度。",
        "solution": "从深度/语义层估计虚拟焦平面，按距离对不同层做 blur、色彩和饱和度处理，保留主体层锐度。",
        "inputs": "video + depth/scene parsing + motion field。",
        "model": "depth-layer renderer + temporal refinement；生成式模型只补复杂边界。",
        "training": "城市/建筑/风景视频、真实 tilt-shift 镜头参考、深度标注和合成焦平面。",
        "loss": "depth-layer consistency + edge/alpha + perceptual style + temporal stability。",
        "temporal": "焦平面参数由用户控制，低频稳定；深度层局部更新。",
        "edge": "实时预览可采用 2-3 层近似；录后增加细分层。",
        "risks": "深度错误导致局部错焦；创意效果可能显得廉价；动态物体边界复杂。",
        "mvp": "建筑/静态街景，固定焦平面方向和两种强度。",
    },
    {
        "op_id": "OP-027", "title": "事件触发慢动作与局部插帧", "english": "Event-triggered slow motion with local frame interpolation", "family": "temporal_exposure",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["official_dji_subject_tracking", "local_flashvsr"],
        "problem": "全程高帧率耗电且存储大，但真正有价值的动作只占很短片段。",
        "solution": "用音频、运动和语义事件触发 ring buffer，录制前后保留短片段；仅对主体 ROI 或事件窗口插帧。",
        "inputs": "低帧率视频 + ring buffer + IMU + audio + subject tracks。",
        "model": "轻量 event detector + local frame interpolation/flow model。",
        "training": "体育、儿童、宠物、舞台动作；标注事件边界和用户认为值得慢放的片段。",
        "loss": "interpolation reconstruction + flow consistency + occlusion handling + event boundary smoothness。",
        "temporal": "事件触发必须有 hysteresis 和 pre-roll/post-roll，避免重复触发。",
        "edge": "检测放 DSP/NPU，插帧在录后或片段停止后做。",
        "risks": "错过事件或错误触发；快速遮挡时插帧伪影；用户不理解为什么保存了额外片段。",
        "mvp": "声音/动作触发两个事件类别，固定 3 秒 ring buffer 和 2x 插帧。",
    },
    {
        "op_id": "OP-035", "title": "说话人语义自动拉焦", "english": "Speaker-aware semantic focus pull", "family": "virtual_camera",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["official_apple_cinematic_mode", "official_sony_real_time_tracking"],
        "problem": "自动拉焦通常只根据最近/最大的人脸，无法理解对话中的说话人和视线。",
        "solution": "将声源、人脸 track、视线、人物重要性组合成 focus policy，并使用 hysteresis 控制切换。",
        "inputs": "audio DOA + face/pose/eye gaze + depth + AF state。",
        "model": "audio-visual association + low-latency policy network + focus trajectory smoother。",
        "training": "双人/多人对话，标注焦点选择、切换时机和用户偏好；加入遮挡、转头和抢话。",
        "loss": "speaker association + focus target classification + transition smoothness + wrong-switch penalty。",
        "temporal": "最短 dwell time、切换冷却和关键帧 confidence；失去声源时回到视觉目标。",
        "edge": "声源特征由 DSP，脸部/深度由 NPU；适合在线预览和录像。",
        "risks": "混响或多人抢话造成错误焦点；过于智能的切换会打扰摄影师控制。",
        "mvp": "双人采访，支持自动/半自动两种模式和手动锁定。",
    },
    {
        "op_id": "OP-043", "title": "双摄联合去模糊与细节补偿", "english": "Dual-camera deblurring and detail compensation", "family": "multi_camera",
        "mode": "offline_device", "truth": "faithful", "source_ids": ["local_flashvsr", "official_samsung_super_steady"],
        "problem": "主摄在低照度有噪声和运动模糊，长焦有细节但更不稳定，单路去模糊容易 hallucinate。",
        "solution": "将两路摄像头按时空和视场对齐，利用长焦细节作为受控 reference，主摄作为稳定/曝光底图。",
        "inputs": "同步多摄 RAW/YUV + calibration + IMU + flow + exposure metadata。",
        "model": "cross-view alignment + confidence-aware feature fusion + restoration decoder。",
        "training": "同步双摄运动视频、真实模糊/噪声、不同焦段标定；训练时随机失配和曝光差。",
        "loss": "cross-view photometric + reconstruction + confidence calibration + temporal consistency + edge detail。",
        "temporal": "参考摄像头选择随运动/亮度变化，切换时共享 feature state。",
        "edge": "适合 1080p 在线或 4K 录后；高分辨率融合应限制 ROI。",
        "risks": "视差/同步误差、不同 lens response 和遮挡导致 ghosting。",
        "mvp": "主摄+长焦固定焦段，静态/缓慢运动夜景，比较单摄和双摄细节与伪影。",
    },
    {
        "op_id": "OP-051", "title": "滚动快门与电子防抖联合校正", "english": "Joint rolling-shutter and EIS correction", "family": "motion_quality",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["local_flashvsr", "official_gopro_horizon_lock"],
        "problem": "快速摇摄时逐行曝光造成倾斜/弯曲，EIS 再裁切会放大几何不一致。",
        "solution": "显式使用 row-time model、IMU 和 flow，把滚动快门校正放进稳定优化，而不是后置单独处理。",
        "inputs": "RAW/YUV + row exposure timing + IMU + lens calibration + flow。",
        "model": "row-wise warp + camera pose estimator + causal stabilization controller。",
        "training": "真实高速旋转视频、IMU 对齐数据、合成 row-time distortion；加入不同读出速度。",
        "loss": "geometric reprojection + line straightness + horizon stability + temporal warp + crop penalty。",
        "temporal": "姿态使用高频 IMU，纹理 flow 使用短窗口；异常 IMU 时降级到普通 EIS。",
        "edge": "更适合 ISP/DSP 前置校正，几何模型比生成模型更适合端侧。",
        "risks": "光流和 IMU 不一致时会变形；大滚快门畸变可能无法从单帧恢复。",
        "mvp": "快速水平摇摄和骑行两类，测直线弯曲、裁切和稳定自然度。",
    },
    {
        "op_id": "OP-059", "title": "逆光人像局部 HDR 与身份保持", "english": "Backlit portrait local HDR with identity preservation", "family": "night_hdr",
        "mode": "online_recording", "truth": "perceptual", "source_ids": ["local_authface", "local_tiger", "official_google_video_boost"],
        "problem": "全局 HDR 会让逆光人脸灰、背景过曝或视频帧间呼吸；人脸增强又可能改变身份。",
        "solution": "以人脸/人体 ROI 独立做 tone mapping 和 detail restoration，使用身份 embedding 与肤色稳定约束，背景保留真实高光滚降。",
        "inputs": "multi-frame YUV/RAW + face/body mask + exposure metadata + motion。",
        "model": "local tone mapping + portrait restoration branch + temporal fusion。",
        "training": "逆光人像视频、多曝光配对、不同肤色和光源；合成高光裁切、噪声和压缩。",
        "loss": "ROI reconstruction + identity + skin-tone + temporal color + highlight roll-off + boundary consistency。",
        "temporal": "肤色/低频亮度使用 track state；表情细节使用短期参考。",
        "edge": "适合在线 1080p，4K 只处理 face ROI；高质量模式录后重算。",
        "risks": "肤色过度美化、背景与人物光照不匹配、逆光高光不可恢复。",
        "mvp": "窗边和日落两场景，单人半身，测肤色偏差、identity cosine、flicker。",
    },
    {
        "op_id": "OP-067", "title": "眼镜反光和眼神光联合处理", "english": "Eyeglass glare suppression and catchlight control", "family": "portrait_identity",
        "mode": "offline_device", "truth": "perceptual", "source_ids": ["local_authface", "local_svfr"],
        "problem": "眼镜反光遮挡瞳孔时，直接修复容易生成错误眼睛；眼神光逐帧变化也会产生不自然跳闪。",
        "solution": "检测镜片/眼睛层，先抑制反光再以身份和前后帧补偿瞳孔结构；眼神光使用显式可控参数。",
        "inputs": "face landmarks + eye/eyeglass mask + consecutive frames + optional reference frame。",
        "model": "eye ROI restoration + reflection separation + identity-conditioned decoder。",
        "training": "戴眼镜人像视频、可控反光拍摄、不同镜片和姿态；人工标注眼睛/镜片/高光。",
        "loss": "eye reconstruction + identity + reflection sparsity + temporal consistency + iris boundary。",
        "temporal": "眼睛 track 单独维护 reference；眨眼期间冻结或降低生成强度。",
        "edge": "只在眼睛 ROI 录后处理，避免全脸模型成本。",
        "risks": "幻觉眼睛、瞳孔方向错误、反光真实语义被删除。",
        "mvp": "固定眼镜类型、正面人像，支持开关和强度滑杆。",
    },
    {
        "op_id": "OP-075", "title": "天空替换与地面光照联动", "english": "Temporal sky replacement with ground-light coupling", "family": "scene_editing",
        "mode": "offline_device", "truth": "generative", "source_ids": ["official_capcut_video_cutout", "local_fluxir"],
        "problem": "单独替换天空会使地面、人物边缘和环境色温不匹配，视频中天空还会抖动或穿帮。",
        "solution": "天空 segmentation + camera motion + replacement sky trajectory + ground illumination adjustment；保持原始主体区域可回退。",
        "inputs": "video + sky mask + scene depth/segmentation + IMU + optional text/reference sky。",
        "model": "sky tracker + compositing + low-frequency relighting; generative model only for sky synthesis/outpainting。",
        "training": "多天气天空视频、真实地面光照和人物边界；合成天光方向、雾和动态云。",
        "loss": "sky reconstruction + boundary alpha + color/illumination consistency + temporal motion + semantic preservation。",
        "temporal": "天空作为全局层稳定，地面光照低频调整；云运动由用户速度或原始相机运动驱动。",
        "edge": "实时预览只做替换，地面联动录后完成。",
        "risks": "发丝/树枝穿帮、地面颜色不自然、生成天空改变事件真实性。",
        "mvp": "静态城市/旅行，预置 3 种天空，输出 sky mask 和可回退工程。",
    },
    {
        "op_id": "OP-083", "title": "跨镜头肤色与胶片质感连续", "english": "Cross-lens skin tone and film-look continuity", "family": "color_science",
        "mode": "online_recording", "truth": "perceptual", "source_ids": ["official_blackmagic_gen5_color", "official_panasonic_real_time_lut", "official_sony_s_cinetone"],
        "problem": "多摄切镜不仅有曝光差，肤色和颗粒风格也会跳变。",
        "solution": "维护全局 look state，以脸部/肤色和灰阶区域作为 anchor，分别校正不同摄像头的 color response。",
        "inputs": "multi-camera YUV/Log + face/skin mask + exposure/ISO + lens metadata。",
        "model": "camera-specific color transform + stateful look controller + semantic LUT。",
        "training": "多摄同步拍摄 color chart、人像和不同光线；跨镜头 reference look 标定。",
        "loss": "skin-tone deviation + cross-lens color + temporal look smoothness + grain spectrum。",
        "temporal": "切换前进行 look state warm-up，切换时连续插值，不重置颗粒相位。",
        "edge": "适合 ISP/GPU 实时；颗粒和 halation 可采用低成本 procedural 版本。",
        "risks": "过度肤色校正、不同肤色公平性、Log/Rec709 状态混用。",
        "mvp": "主摄/超广/长焦三镜头，单人移动，比较普通切镜与 look continuity。",
    },
    {
        "op_id": "OP-091", "title": "音频触发精彩瞬间与局部慢放", "english": "Audio-triggered highlight capture and local slow motion", "family": "audio_visual",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["official_dji_active_track", "official_blackmagic_camera_app"],
        "problem": "用户常常错过进球、掌声、笑声或儿童动作的关键前后瞬间。",
        "solution": "音频事件检测与视觉运动强度联合触发 ring buffer，保存事件窗口并给出局部慢放候选。",
        "inputs": "microphone array + video proxy + IMU + motion/subject detector。",
        "model": "tiny audio event classifier + vision motion scorer + rule/policy layer。",
        "training": "真实生活和运动声音、不同噪声场景、事件边界标注；用用户选择作为 ranking supervision。",
        "loss": "event classification + temporal boundary + highlight ranking + false-trigger penalty。",
        "temporal": "pre-roll/post-roll、触发冷却和事件合并；避免连续掌声生成多个片段。",
        "edge": "DSP + low-res NPU，适合持续运行；后续局部插帧可异步。",
        "risks": "噪声误触发、私密音频处理、存储和用户隐私。",
        "mvp": "掌声、笑声、撞击声三类事件，保存前后 2 秒。",
    },
    {
        "op_id": "OP-099", "title": "视频扩散的局部事实保护编辑", "english": "Localized video diffusion editing with fact-region protection", "family": "generative_video",
        "mode": "cloud_render", "truth": "generative", "source_ids": ["local_dit", "local_magvit", "local_fluxir"],
        "problem": "全视频扩散编辑会重绘原始区域，导致人物、文字和动作改变。",
        "solution": "构建 protected region / editable region mask，原视频区域采用 latent inpainting constraints，只有指定区域允许生成。",
        "inputs": "video + edit mask + text/reference condition + optical flow/depth。",
        "model": "video latent diffusion/DiT + mask adapter + temporal attention；手机只负责上传/预览和 mask。",
        "training": "视频局部编辑数据、mask/文本/参考图三元组、区域冻结训练；加入文字、人脸和动作保护。",
        "loss": "protected-region reconstruction + editable-region diffusion objective + temporal consistency + identity/text preservation。",
        "temporal": "关键帧生成后通过 feature propagation 扩散，保护区尽量 copy/warp。",
        "edge": "云端或高端录后；必须输出生成 mask、原始视频 hash 和编辑参数。",
        "risks": "生成区域边界、文字和人脸身份；云端隐私与版权问题。",
        "mvp": "只做天空/背景色/雨雪等低风险区域，禁改脸和文字。",
    },
    {
        "op_id": "OP-107", "title": "温度感知的算法质量伸缩", "english": "Thermal-aware quality scaling for video algorithms", "family": "capture_assistance",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["local_flashvsr", "local_wfvae", "official_google_video_boost"],
        "problem": "手机录像的模型质量不能只按峰值算力设计，温度、电量、后台负载会导致中途掉帧和突然降质。",
        "solution": "建立 quality ladder：模型宽度、参考帧数、ROI 范围、分辨率和后处理队列随热状态连续降级。",
        "inputs": "temperature/battery/SoC load + video mode + scene complexity + model latency telemetry。",
        "model": "多级模型或 early-exit/adapter；调度器在 CPU 上运行，模型在 NPU/GPU。",
        "training": "不同设备、温度、负载和片段长度的 profiling 数据；建立质量-延迟-功耗曲线。",
        "loss": "任务质量 + temporal stability + latency/power regularizer；训练权重不代替真实设备 profiling。",
        "temporal": "降级/升级使用 hysteresis，不能每帧切换；关键帧保持相同质量等级。",
        "edge": "直接面向端侧部署，必须联动编码器、内存和后台任务。",
        "risks": "用户感知到中途画质跳变；不同 SoC 的 profile 不可直接迁移。",
        "mvp": "两档温控和三档模型，录制 10 分钟观察 FPS、温度和质量变化。",
    },
    {
        "op_id": "OP-005", "title": "动态污渍/雨滴检测与可逆抑制", "english": "Dynamic contamination detection with reversible suppression", "family": "computational_optics",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["official_davinci_magic_mask", "local_flashvsr"],
        "problem": "手机录像中雨滴或手指遮挡会在几秒内改变，静态 lens mask 不够。",
        "solution": "检测透明/半透明污染并输出 mask/confidence；低置信度只做提示，避免强生成抹掉真实内容。",
        "inputs": "连续帧 + local contrast/flow + lens metadata + scene motion。",
        "model": "轻量 contamination detector + mask tracker + conservative temporal filter。",
        "training": "真实雨滴、指纹、灰尘、贴膜和逆光高光；hard negative 包含水面反光和灯光。",
        "loss": "mask BCE/Dice + temporal mask consistency + false-positive penalty + transparency regression。",
        "temporal": "污染 mask 有长寿命状态，真实场景高光短寿命；使用双时间常数。",
        "edge": "可实时运行，强修复单独触发。",
        "risks": "误判真实高光或前景；检测器误报影响用户信任。",
        "mvp": "只做提示和局部降低锐化，不直接生成清除。",
    },
    {
        "op_id": "OP-013", "title": "舞台追光与人物 track 联动", "english": "Stage spotlight following with subject tracks", "family": "relighting",
        "mode": "offline_device", "truth": "generative", "source_ids": ["official_dji_subject_tracking", "local_fluxir"],
        "problem": "舞台录像中人物和灯光快速运动，手工加追光成本高，逐帧生成又容易跟丢。",
        "solution": "用 person track、舞台区域和音乐节拍控制虚拟 spotlight；追光只影响可选光照层，不修改人物身份。",
        "inputs": "person tracks + stage segmentation + audio beat + background brightness map。",
        "model": "tracking + parametric spotlight renderer + optional relighting adapter。",
        "training": "舞台/演唱会视频、光源轨迹和人群遮挡；合成不同 spotlight 半径和颜色。",
        "loss": "track consistency + light falloff + boundary/occlusion + temporal intensity + perceptual style。",
        "temporal": "追光位置由 track 预测，强度/颜色低通；人物出场/退场使用 fade in/out。",
        "edge": "预览可做简单光斑，录后做人物受光和阴影。",
        "risks": "舞台真实灯光与虚拟灯叠加不协调；多人场景光斑竞争。",
        "mvp": "单人舞台、一个追光、三种颜色和强度，测跟随丢失率。",
    },
    {
        "op_id": "OP-021", "title": "多层深度与遮挡感知焦点切换", "english": "Occlusion-aware multi-layer focus transitions", "family": "depth_focus",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["official_apple_cinematic_mode", "official_sony_real_time_tracking"],
        "problem": "前景遮挡、人物交错和快速走入画面时，简单人脸焦点会跳到错误主体。",
        "solution": "维护 scene graph/occlusion graph 和焦点候选列表，焦点切换由视线、说话、距离和用户锁定共同决定。",
        "inputs": "multi-layer depth + face/body tracks + gaze + audio + focus state。",
        "model": "occlusion-aware tracker + focus policy + differentiable blur compositor。",
        "training": "多人走动、前景遮挡、采访和舞台视频；标注 focus target/transition timing。",
        "loss": "target classification + focus trajectory + boundary blur + switch penalty + temporal identity。",
        "temporal": "最短保持时间、切换冷却、关键帧重估；遮挡后先恢复旧 track 再切换。",
        "edge": "适合在线，但需使用硬件 AF/Depth 低延迟输入。",
        "risks": "策略错误比传统 AF 更显眼；用户对自动切换缺少信任。",
        "mvp": "双人对话+前景遮挡，提供自动/手动/锁定三种模式。",
    },
    {
        "op_id": "OP-037", "title": "数字变焦中的主体细节增强", "english": "Subject-aware detail enhancement for digital zoom", "family": "virtual_camera",
        "mode": "online_recording", "truth": "perceptual", "source_ids": ["local_fluxsr", "local_flashvsr", "official_samsung_super_steady"],
        "problem": "数字变焦放大后，主体细节不足；全画面超分成本高且容易生成背景伪影。",
        "solution": "根据 subject/face/文本区域分配超分预算，背景使用传统重采样，主体使用时序 restoration/super-resolution。",
        "inputs": "video + subject masks + zoom factor + motion + multi-camera reference optional。",
        "model": "ROI video SR/one-step distillation + lightweight background scaler。",
        "training": "真实手机 zoom 视频、长焦 reference、压缩/噪声/运动退化；加入不同主体类别。",
        "loss": "ROI reconstruction + perceptual + identity/detail + temporal warp + background smoothness。",
        "temporal": "ROI track 共享 feature state，变焦变化时逐渐调整模型强度；避免瞬时锐化变化。",
        "edge": "适合实时局部增强，4K 输出需分块/异步。",
        "risks": "人脸和文字 hallucination；ROI 切换造成锐度边界；长焦参考视差。",
        "mvp": "2x/3x 数字变焦的人像和文字牌，输出原始/增强对比和置信度。",
    },
    {
        "op_id": "OP-053", "title": "局部非刚性运动视频复原", "english": "Local non-rigid video restoration", "family": "motion_quality",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["local_flashvsr", "local_svfr", "local_tiger"],
        "problem": "人体、宠物、树叶等非刚性区域不能直接用全局光流对齐，容易出现重复纹理和错位。",
        "solution": "将 global camera motion、object track 和 local deformation 分层，局部区域使用 deformable alignment 和置信度融合。",
        "inputs": "video + global flow/IMU + semantic masks + object tracks。",
        "model": "deformable temporal transformer/recurrent restoration + confidence map。",
        "training": "真实非刚性视频、合成局部运动/遮挡/模糊；按人体、宠物、树叶和水面分层采样。",
        "loss": "deformable alignment + reconstruction + edge/texture + temporal consistency + confidence calibration。",
        "temporal": "对象级 reference bank，遮挡时降低历史参考权重；重新出现时 warm-up。",
        "edge": "局部 ROI 运行，避免全画面高成本。",
        "risks": "局部纹理幻觉、人体结构错位、置信度估计不准。",
        "mvp": "人脸/手部/宠物三类 ROI，重点测 identity/shape 与 flicker。",
    },
    {
        "op_id": "OP-061", "title": "霓虹与高亮点的时序颜色记忆", "english": "Temporal color memory for neon and point highlights", "family": "night_hdr",
        "mode": "online_recording", "truth": "faithful", "source_ids": ["official_google_video_boost", "local_flashvsr"],
        "problem": "霓虹灯和车灯在视频中容易因曝光、压缩和降噪发生颜色跳变。",
        "solution": "对高亮点建立 persistent light IDs，维护颜色/强度/形状状态，区别真实光源变化与算法噪声。",
        "inputs": "YUV/RAW + highlight detector + optical flow + exposure metadata。",
        "model": "point-light tracker + color-state filter + local tone mapping。",
        "training": "夜景城市、车灯、LED 屏、舞台；加入 flicker frequency、过曝和色偏。",
        "loss": "color trajectory + highlight shape + temporal smoothness + exposure-aware reconstruction。",
        "temporal": "颜色状态低通、高亮进入/离开 fade；LED 真实频闪要保留而非全部抹平。",
        "edge": "轻量 tracker 可实时；高质量 tone mapping 录后。",
        "risks": "错误平滑真实灯光变化；不同光源颜色被混合；高亮饱和区域信息不可恢复。",
        "mvp": "城市车灯和 LED 屏两个场景，分别测颜色稳定和真实闪烁保留。",
    },
    {
        "op_id": "OP-069", "title": "头发、眼睛和牙齿的区域化增强", "english": "Region-aware hair, eye, and teeth enhancement", "family": "portrait_identity",
        "mode": "online_recording", "truth": "perceptual", "source_ids": ["local_tiger", "local_authface", "local_heads_up"],
        "problem": "全脸美化对头发、眼睛、牙齿使用不同频率和颜色策略，统一处理会造成假发、塑料眼睛和过白牙齿。",
        "solution": "parsing mask + ROI-specific experts：头发保留高频方向，眼睛保结构与 catchlight，牙齿做受控色彩。",
        "inputs": "face/body parsing + landmarks + track ID + temporal ROI features。",
        "model": "shared encoder + region-specific lightweight heads + temporal fusion。",
        "training": "人像视频、区域标注、不同妆容/发型/牙齿颜色；合成压缩、模糊、低照度和遮挡。",
        "loss": "region reconstruction + perceptual + identity + hair orientation/eye boundary/teeth color regularizers + temporal consistency。",
        "temporal": "区域独立状态，眨眼/说话/头发大运动时改变 reference 权重。",
        "edge": "优先 face ROI，按区域重要性分配 NPU 预算。",
        "risks": "过度改变外貌；训练数据偏差；parsing 错误会影响背景。",
        "mvp": "只增强眼睛和头发，不改变脸型，提供强度上限和原片回退。",
    },
]


def main() -> None:
    pool = {row["id"]: row for row in (json.loads(line) for line in OPPORTUNITIES.read_text(encoding="utf-8").splitlines() if line.strip())}
    rows = []
    for card in CARDS[:30]:
        base = pool.get(card["op_id"], {})
        row = {**base, **card, "deep_dive_id": f"DD-{len(rows)+1:02d}", "last_verified": str(date.today())}
        rows.append(row)
    OUT.write_text("\n".join(json.dumps(row, ensure_ascii=False) for row in rows) + "\n", encoding="utf-8")
    lines = ["# 30 个技术深度方向", "", "本文件把候选机会转换为可讨论的技术卡。卡片中的训练损失权重均为工程起始假设，除非来源明确披露，否则不能作为论文原始配置。", ""]
    for row in rows:
        lines += [
            f"## {row['deep_dive_id']} {row['title']} ({row['english']})",
            f"- 能力族：{row['family']}；模式：{row['mode']}；真实性边界：{row['truth']}",
            f"- 证据：{', '.join(row['source_ids'])}",
            f"- 研究问题：{row['problem']}",
            f"- 技术方案：{row['solution']}",
            f"- 输入信号：{row['inputs']}",
            f"- 模型链路：{row['model']}",
            f"- 数据制作：{row['training']}",
            f"- LOSS/目标：{row['loss']}",
            f"- 时序策略：{row['temporal']}",
            f"- 端侧落点：{row['edge']}",
            f"- 风险：{row['risks']}",
            f"- MVP：{row['mvp']}",
            "",
        ]
    NOTE.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(rows)} deep-dive records to {OUT}")


if __name__ == "__main__":
    main()
