import csv
import json
from pathlib import Path

from tools.enc_dec_library.config import ROOT


ARCHITECTURE_ROWS = [
    {
        "model": "VAE",
        "family": "image continuous latent",
        "year": 2014,
        "encoder": "amortized inference network predicts mean and variance",
        "bottleneck": "Gaussian latent with reparameterization",
        "decoder": "likelihood/generative network",
        "compression": "task-dependent; no fixed modern f8 contract",
        "latent_channels_or_tokens": "task-dependent",
        "causal": "no",
        "dit_role": "the probabilistic foundation of continuous latent autoencoders",
        "evidence_status": "primary-source-indexed",
        "evidence_anchor": "source_manifest key=vae",
        "notes": "Foundational theory; local complete PDF download remains pending.",
    },
    {
        "model": "VQ-VAE",
        "family": "image discrete tokenizer",
        "year": 2017,
        "encoder": "convolutional encoder",
        "bottleneck": "nearest-neighbor vector quantization with learned codebook",
        "decoder": "convolutional decoder",
        "compression": "configuration-dependent",
        "latent_channels_or_tokens": "discrete code indices",
        "causal": "no",
        "dit_role": "foundation for discrete image/video tokenizers and autoregressive generation",
        "evidence_status": "primary-source-indexed",
        "evidence_anchor": "source_manifest key=vqvae",
        "notes": "PDF download pending; indexed from the primary paper metadata.",
    },
    {
        "model": "VQGAN",
        "family": "image discrete tokenizer",
        "year": 2021,
        "encoder": "convolutional encoder with residual and attention blocks",
        "bottleneck": "vector-quantized 2D grid",
        "decoder": "convolutional decoder trained for perceptual realism",
        "compression": "typically f16 in the paper's high-resolution tokenizer settings",
        "latent_channels_or_tokens": "2D code grid",
        "causal": "no",
        "dit_role": "established perceptual-adversarial tokenizer training",
        "evidence_status": "paper-verified",
        "evidence_anchor": "vqgan PDF p3 Fig.2; p8 Table 5",
        "notes": "Useful baseline for modern tokenizer loss design.",
    },
    {
        "model": "LDM / SD-VAE",
        "family": "image continuous KL autoencoder",
        "year": 2022,
        "encoder": "2D convolutional ResNet encoder",
        "bottleneck": "regularized continuous latent",
        "decoder": "2D convolutional ResNet decoder",
        "compression": "f4-f32 studied; f8 became the common production point",
        "latent_channels_or_tokens": "commonly 4 channels at f8",
        "causal": "no",
        "dit_role": "moves diffusion from pixels to a frozen compressed latent space",
        "evidence_status": "paper-verified+code-verified",
        "evidence_anchor": "ldm PDF p2 Sec.3; source_code/ldm/autoencoder.py",
        "notes": "Separates autoencoder pretraining from latent diffusion training.",
    },
    {
        "model": "DiT latent interface",
        "family": "frozen image VAE plus transformer",
        "year": 2023,
        "encoder": "pretrained frozen Stable Diffusion VAE encoder",
        "bottleneck": "latent grid patchified into transformer tokens",
        "decoder": "pretrained frozen Stable Diffusion VAE decoder",
        "compression": "f8 VAE; DiT adds latent patch size p",
        "latent_channels_or_tokens": "4-channel latent in original DiT setup",
        "causal": "no",
        "dit_role": "canonical frozen-VAE DiT training pattern",
        "evidence_status": "paper-verified+code-verified",
        "evidence_anchor": "dit PDF p3 Fig.3, p4 Fig.4, p13 Table 5; source_code/dit/models.py",
        "notes": "The VAE is an interface and quality ceiling, not jointly trained with DiT.",
    },
    {
        "model": "SD3 VAE",
        "family": "image continuous KL autoencoder",
        "year": 2024,
        "encoder": "2D ResNet encoder with mid attention",
        "bottleneck": "continuous latent normalized by shift/scale",
        "decoder": "mirrored 2D ResNet decoder",
        "compression": "f8",
        "latent_channels_or_tokens": "16 channels",
        "causal": "no",
        "dit_role": "higher-capacity latent for MM-DiT and rectified flow",
        "evidence_status": "paper-verified+code-verified",
        "evidence_anchor": "sd3 PDF p7 Table 3, App.B.2; source_code/sd3/sd3_impls.py:97-107,247-310",
        "notes": "The paper reports architecture selection, not the complete VAE training recipe.",
    },
    {
        "model": "FLUX.1 AE",
        "family": "image continuous autoencoder",
        "year": 2024,
        "encoder": "2D ResNet encoder with mid attention",
        "bottleneck": "16-channel latent with shift/scale normalization",
        "decoder": "mirrored 2D ResNet decoder",
        "compression": "f8 inferred from four resolution levels",
        "latent_channels_or_tokens": "16 channels",
        "causal": "no",
        "dit_role": "pixel-latent interface for FLUX flow transformer",
        "evidence_status": "code-verified",
        "evidence_anchor": "source_code/flux/modules/autoencoder.py; source_code/flux/util.py:539-548",
        "notes": "Public code exposes architecture/config; complete AE training data and loss recipe are undisclosed.",
    },
    {
        "model": "TiTok",
        "family": "image discrete 1D tokenizer",
        "year": 2024,
        "encoder": "ViT encoder consumes image patches and K learnable latent tokens",
        "bottleneck": "K vector-quantized 1D tokens",
        "decoder": "ViT decoder reconstructs image from quantized tokens and mask tokens",
        "compression": "32-256 tokens; 32-token flagship at 256px",
        "latent_channels_or_tokens": "K tokens; codebook 4096 in final setting",
        "causal": "no",
        "dit_role": "shows token count can be decoupled from a fixed 2D grid",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2406.07550 lines 106-180,189-223; Fig.3",
        "notes": "Primarily paired with MaskGIT, but materially informs DiT token-budget design.",
    },
    {
        "model": "DC-AE",
        "family": "image continuous high-compression autoencoder",
        "year": 2025,
        "encoder": "residual autoencoding with space-to-channel shortcut",
        "bottleneck": "continuous latent at f32/f64/f128",
        "decoder": "channel-to-space mirrored reconstruction path",
        "compression": "up to f128; f64 emphasized for DiT acceleration",
        "latent_channels_or_tokens": "configuration-dependent continuous latent",
        "causal": "no",
        "dit_role": "moves token compression from DiT patchify into the autoencoder",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2410.10733 lines 46-82; Fig.10",
        "notes": "High compression requires optimization and high-resolution adaptation, not merely deeper downsampling.",
    },
    {
        "model": "MAGVIT",
        "family": "video discrete tokenizer",
        "year": 2023,
        "encoder": "3D VQ encoder",
        "bottleneck": "discrete video tokens",
        "decoder": "3D VQ decoder",
        "compression": "architecture/configuration-dependent",
        "latent_channels_or_tokens": "3D discrete token grid",
        "causal": "task-aware; not the same streaming contract as Wan",
        "dit_role": "unified image/video tokenization and masked token generation baseline",
        "evidence_status": "paper-verified",
        "evidence_anchor": "magvit PDF p3 Fig.2, p8 Table 7",
        "notes": "A key ancestor for later causal video tokenizers.",
    },
    {
        "model": "MAGVIT-v2",
        "family": "video/image discrete tokenizer",
        "year": 2024,
        "encoder": "temporally causal convolutional encoder",
        "bottleneck": "lookup-free quantization (LFQ)",
        "decoder": "temporally causal decoder",
        "compression": "configuration-dependent",
        "latent_channels_or_tokens": "binary-factorized discrete codes",
        "causal": "yes",
        "dit_role": "strong causal tokenizer design reused by later video systems",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2310.05737 Fig.7 and tokenizer sections",
        "notes": "Discrete tokenizer; mainly autoregressive use, but architecture is widely inherited.",
    },
    {
        "model": "CogVideoX 3D VAE",
        "family": "video continuous causal VAE",
        "year": 2025,
        "encoder": "temporally causal 3D convolutional encoder",
        "bottleneck": "regularized continuous video latent",
        "decoder": "temporally causal 3D convolutional decoder",
        "compression": "T x H x W = 4 x 8 x 8",
        "latent_channels_or_tokens": "paper studies 4/8/16/32 channels; release config must be checked per checkpoint",
        "causal": "yes",
        "dit_role": "production-scale causal video VAE with context parallelism",
        "evidence_status": "paper-verified+code-verified",
        "evidence_anchor": "ar5iv_2408.06072 Fig.4; source_code/cogvideox/.../cp_enc_dec.py:743-998",
        "notes": "Do not assume one latent-channel count across all released variants.",
    },
    {
        "model": "Open-Sora 1.2 VAE",
        "family": "hybrid image plus video autoencoder",
        "year": 2025,
        "encoder": "frozen SDXL 2D VAE followed by MAGVIT-v2-style 3D VAE",
        "bottleneck": "continuous video latent aligned through staged training",
        "decoder": "3D temporal reconstruction followed by 2D VAE pixel decoder",
        "compression": "T x H x W = 4 x 8 x 8",
        "latent_channels_or_tokens": "not fully specified in report",
        "causal": "yes",
        "dit_role": "practical bootstrapping of video compression from a pretrained image VAE",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2412.20404 lines 56-66 and 166-180; Fig.5",
        "notes": "A clear example of staged feature reconstruction before direct RGB video reconstruction.",
    },
    {
        "model": "WF-VAE",
        "family": "video continuous causal VAE",
        "year": 2025,
        "encoder": "3D causal backbone plus multi-level wavelet energy-flow path",
        "bottleneck": "continuous video latent enriched with low-frequency energy",
        "decoder": "mirrored backbone plus wavelet outflow and causal cache",
        "compression": "model variants evaluated at common video VAE ratios",
        "latent_channels_or_tokens": "configuration-dependent",
        "causal": "yes",
        "dit_role": "improves reconstruction and block-wise decoding consistency",
        "evidence_status": "paper-verified",
        "evidence_anchor": "wfvae PDF p3 Fig.2, p4 Fig.3, p7-8 ablations",
        "notes": "Wavelet loss weight 0.1 and L1 outperform L2 in reported ablation.",
    },
    {
        "model": "VidTok",
        "family": "video continuous or discrete tokenizer",
        "year": 2025,
        "encoder": "open modular spatiotemporal encoder",
        "bottleneck": "continuous KL or discrete FSQ alternatives",
        "decoder": "decoder supports high-resolution-only fine-tuning",
        "compression": "multiple settings under a unified benchmark",
        "latent_channels_or_tokens": "configuration-dependent",
        "causal": "variant-dependent",
        "dit_role": "controlled study of architecture, quantization and training choices",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2412.13061 lines 40-60; Fig.2, Fig.4, Fig.6",
        "notes": "Two-stage low-resolution pretraining then high-resolution decoder fine-tuning.",
    },
    {
        "model": "LTX-Video VAE",
        "family": "video continuous causal denoising VAE",
        "year": 2025,
        "encoder": "causal 3D encoder with patchification moved into VAE",
        "bottleneck": "high-dimensional latent, first frame encoded separately",
        "decoder": "timestep-conditioned denoising decoder with multi-layer noise injection",
        "compression": "T x H x W = 8 x 32 x 32; pixel-to-latent ratio 1:192",
        "latent_channels_or_tokens": "high-dimensional continuous latent",
        "causal": "yes",
        "dit_role": "jointly optimizes tokenizer and final denoising behavior for real-time DiT",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2501.00103 lines 184-242; Fig.2, Fig.4",
        "notes": "Decoder is more than inverse compression: it performs the final latent-to-pixel denoising step.",
    },
    {
        "model": "Cosmos Tokenizer",
        "family": "video continuous and discrete causal tokenizers",
        "year": 2025,
        "encoder": "3D Haar wavelet, causal residual/downsampling, spatiotemporal attention",
        "bottleneck": "continuous KL-like or discrete FSQ-style variants",
        "decoder": "mirrored causal architecture; optional diffusion decoder for discrete tokens",
        "compression": "continuous 4/8 x 8 x 8; discrete 8 x 16 x 16 variants",
        "latent_channels_or_tokens": "variant-dependent",
        "causal": "yes; first frame separately preserved",
        "dit_role": "unified image/video tokenizer at world-model scale",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2501.03575 tokenizer section; Fig. network architecture, Fig.11, Fig.15",
        "notes": "Explicitly supports both continuous diffusion and discrete autoregressive modeling.",
    },
    {
        "model": "Wan VAE / WanDecoder",
        "family": "video continuous causal VAE",
        "year": 2025,
        "encoder": "causal 3D ResNet with feature cache and temporal/spatial downsampling",
        "bottleneck": "16-channel Gaussian latent",
        "decoder": "full causal 3D VAE decoder with mirrored temporal/spatial upsampling",
        "compression": "T x H x W = 4 x 8 x 8",
        "latent_channels_or_tokens": "16 channels",
        "causal": "yes",
        "dit_role": "base latent interface and original high-cost decoder in FlashVSR",
        "evidence_status": "paper-verified+code-verified",
        "evidence_anchor": "ar5iv_2503.20314 Fig.5-8; source_code/wan/wan/modules/vae.py:492-644",
        "notes": "FlashVSR's WanDecoder means this full path, not TCDecoder.",
    },
    {
        "model": "FlashVSR LQ_proj_in",
        "family": "restoration condition projector",
        "year": 2026,
        "encoder": "LR RGB is pixel-unshuffled/projected by causal 3D convolutions",
        "bottleneck": "feature tensor aligned to the Wan DiT latent input space",
        "decoder": "not applicable",
        "compression": "spatial rearrangement plus temporal causal projection",
        "latent_channels_or_tokens": "inference model-specific",
        "causal": "yes in streaming stages",
        "dit_role": "injects LQ evidence without running the VAE encoder",
        "evidence_status": "paper-verified+code-verified",
        "evidence_anchor": "flashvsr PDF p4 Fig.2/Sec.3.2; source_code/flashvsr/utils.py:54-95",
        "notes": "This is not a complete encoder and should not be compared as one.",
    },
    {
        "model": "FlashVSR TCDecoder",
        "family": "restoration decoder-only adapter",
        "year": 2026,
        "encoder": "none; consumes predicted latent plus LR conditional path",
        "bottleneck": "Wan latent and LR pixel-shuffle features",
        "decoder": "small causal decoder with 3D pixel shuffle and LR conditioning",
        "compression": "inverts Wan 4 x 8 x 8 scale using PixelShuffle3d(4,8,8)",
        "latent_channels_or_tokens": "latent channels follow Wan; output RGB",
        "causal": "yes",
        "dit_role": "replaces the expensive full Wan decoder at inference",
        "evidence_status": "paper-verified+code-verified",
        "evidence_anchor": "flashvsr PDF p5 Fig.4/Sec.3.4; source_code/flashvsr/TCDecoder.py:73-213",
        "notes": "Decoder-only, trained separately with GT and Wan-decoder distillation targets.",
    },
]


TRAINING_ROWS = [
    {
        "model": "VAE",
        "training_regime": "tokenizer pretraining",
        "trainable_parts": "encoder and decoder",
        "frozen_parts": "none by definition",
        "losses": "negative ELBO = reconstruction likelihood term + KL divergence",
        "staging": "single probabilistic objective",
        "optimizer_schedule": "paper-specific",
        "evidence_status": "primary-source-indexed",
        "evidence_anchor": "vae primary paper",
        "caveat": "Modern perceptual VAEs usually add objectives beyond the original VAE.",
    },
    {
        "model": "VQ-VAE",
        "training_regime": "tokenizer pretraining",
        "trainable_parts": "encoder, codebook, decoder",
        "frozen_parts": "none",
        "losses": "reconstruction + codebook + commitment; straight-through estimator",
        "staging": "tokenizer first, prior model second",
        "optimizer_schedule": "paper-specific",
        "evidence_status": "primary-source-indexed",
        "evidence_anchor": "vqvae primary paper",
        "caveat": "Codebook collapse and dead codes require monitoring.",
    },
    {
        "model": "VQGAN / LDM autoencoder",
        "training_regime": "perceptual tokenizer pretraining",
        "trainable_parts": "encoder, decoder, discriminator, codebook or KL posterior",
        "frozen_parts": "LPIPS feature network",
        "losses": "pixel reconstruction + LPIPS/perceptual + adversarial + codebook or KL regularization",
        "staging": "discriminator is often delayed; latent generative model is trained after tokenizer",
        "optimizer_schedule": "adaptive adversarial weighting in released LDM loss code",
        "evidence_status": "paper-verified+code-verified",
        "evidence_anchor": "vqgan PDF Sec.3; source_code/ldm/vqperceptual.py",
        "caveat": "GAN weight must be tuned after reconstruction is stable.",
    },
    {
        "model": "DiT",
        "training_regime": "frozen-latent diffusion",
        "trainable_parts": "DiT backbone and output head",
        "frozen_parts": "pretrained VAE encoder and decoder",
        "losses": "diffusion noise prediction and learned variance objective",
        "staging": "pre-encode image to latent; train DiT; decode only for sampling/evaluation",
        "optimizer_schedule": "standard DiT training schedule",
        "evidence_status": "paper-verified+code-verified",
        "evidence_anchor": "dit PDF p3-5; source_code/dit/models.py",
        "caveat": "The decoder is a reconstruction ceiling but receives no DiT gradient.",
    },
    {
        "model": "SD3 / MM-DiT",
        "training_regime": "frozen-latent rectified flow",
        "trainable_parts": "MM-DiT flow model",
        "frozen_parts": "16-channel image autoencoder and text encoders",
        "losses": "conditional flow matching / rectified-flow objective",
        "staging": "precompute frozen image and text representations; optional DPO post-training",
        "optimizer_schedule": "timestep sampling and resolution-dependent shifting",
        "evidence_status": "paper-verified",
        "evidence_anchor": "sd3 PDF Sec.4-5, App.E.1",
        "caveat": "The complete VAE pretraining recipe is not disclosed in this paper.",
    },
    {
        "model": "FLUX.1 AE",
        "training_regime": "tokenizer pretraining then frozen-latent flow training",
        "trainable_parts": "undisclosed for AE pretraining; FLUX transformer separately trained",
        "frozen_parts": "AE at standard FLUX inference/training interface",
        "losses": "undisclosed for AE pretraining",
        "staging": "architecture and normalization are public; training recipe is not",
        "optimizer_schedule": "undisclosed",
        "evidence_status": "code-verified+undisclosed",
        "evidence_anchor": "source_code/flux/modules/autoencoder.py; source_code/flux/util.py",
        "caveat": "Do not copy SD3 or LDM loss weights and label them as FLUX facts.",
    },
    {
        "model": "TiTok",
        "training_regime": "two-stage tokenizer training",
        "trainable_parts": "stage 1 full tokenizer; stage 2 decoder only",
        "frozen_parts": "stage 2 encoder and quantizer",
        "losses": "stage 1 proxy-code prediction; stage 2 standard VQGAN pixel/perceptual/adversarial recipe",
        "staging": "warm-up with MaskGIT-VQGAN proxy codes, then decoder fine-tuning",
        "optimizer_schedule": "1M iterations then 500K decoder fine-tuning in final setting",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2406.07550 lines 163-180,223",
        "caveat": "Proxy codes simplify unstable direct RGB/GAN optimization.",
    },
    {
        "model": "DC-AE",
        "training_regime": "decoupled high-resolution autoencoder training",
        "trainable_parts": "autoencoder, with phase-specific subsets",
        "frozen_parts": "phase-dependent",
        "losses": "reconstruction/perceptual first; high-resolution latent adaptation; lightweight local GAN refinement",
        "staging": "low-resolution pretraining -> high-resolution latent adaptation -> local refinement",
        "optimizer_schedule": "phase-specific as reported by DC-AE",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2410.10733 method and Fig.5-6",
        "caveat": "Full-resolution GAN training is intentionally avoided for cost and stability.",
    },
    {
        "model": "Open-Sora 1.2 VAE",
        "training_regime": "three-stage video VAE bootstrapping",
        "trainable_parts": "3D VAE; later stages expand supervision",
        "frozen_parts": "pretrained SDXL 2D VAE initially frozen",
        "losses": "stage 1 reconstruct 2D-VAE features + identity alignment; stage 2 feature reconstruction; stage 3 direct video reconstruction",
        "staging": "0-380K, 380K-640K, 640K-1.2M steps",
        "optimizer_schedule": "local batch 1; 8 GPUs early, 24 GPUs final stage",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2412.20404 lines 66 and HTML S3.SS1",
        "caveat": "An example of curriculum in target space, not merely resolution curriculum.",
    },
    {
        "model": "WF-VAE",
        "training_regime": "video VAE pretraining",
        "trainable_parts": "encoder and decoder including wavelet energy path",
        "frozen_parts": "perceptual feature network if used",
        "losses": "L1 reconstruction + LPIPS/adversarial/KL family + wavelet loss; reported lambda_WL=0.1",
        "staging": "end-to-end with ablated energy-flow and causal-cache design",
        "optimizer_schedule": "paper implementation details",
        "evidence_status": "paper-verified",
        "evidence_anchor": "wfvae PDF p5 implementation, p7-8 ablation",
        "caveat": "Paper reports L1 outperforming L2 in its setting.",
    },
    {
        "model": "VidTok",
        "training_regime": "two-stage resolution curriculum",
        "trainable_parts": "full tokenizer at low resolution; decoder only at high resolution",
        "frozen_parts": "encoder/bottleneck during high-resolution fine-tuning",
        "losses": "continuous or discrete tokenizer objectives plus reconstruction/perceptual components",
        "staging": "low-resolution pretraining -> high-resolution decoder fine-tuning",
        "optimizer_schedule": "lower-FPS data is an explicit motion-learning intervention",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2412.13061 lines 40-60; Fig.6",
        "caveat": "Exact objective differs between continuous and discrete variants.",
    },
    {
        "model": "LTX-Video VAE",
        "training_regime": "joint denoising-aware video VAE training",
        "trainable_parts": "causal encoder, timestep-conditioned decoder, discriminator",
        "frozen_parts": "not a frozen off-the-shelf decoder during tokenizer training",
        "losses": "shared diffusion objective + Reconstruction GAN + reconstruction/perceptual family",
        "staging": "decoder learns final denoising as part of latent-to-pixel reconstruction",
        "optimizer_schedule": "paper-specific",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2501.00103 Sec.2.1.1-2.1.3; Fig.5",
        "caveat": "This deliberately blurs the classic boundary between diffusion last step and decoder.",
    },
    {
        "model": "Wan VAE",
        "training_regime": "video VAE pretraining",
        "trainable_parts": "causal encoder and decoder",
        "frozen_parts": "undisclosed",
        "losses": "complete public loss composition is not fully disclosed in the system report",
        "staging": "feature-cache architecture supports long-video inference",
        "optimizer_schedule": "undisclosed",
        "evidence_status": "paper-verified+code-verified+undisclosed",
        "evidence_anchor": "ar5iv_2503.20314 Wan-VAE section; source_code/wan/wan/modules/vae.py",
        "caveat": "Architecture is auditable; training weights and full data recipe are not.",
    },
    {
        "model": "FlashVSR stages 1-3",
        "training_regime": "restoration adaptation and one-step distillation",
        "trainable_parts": "LoRA rank 384 on Wan DiT plus LQ projection; stage-dependent score/student models",
        "frozen_parts": "pretrained base components except adapters; teacher/real score handled per stage",
        "losses": "stage 1 flow matching; stage 2 flow matching; stage 3 DMD + flow matching + MSE + 2*LPIPS",
        "staging": "joint image-video SR -> block-sparse causal adaptation -> one-step DMD",
        "optimizer_schedule": "AdamW lr 1e-5, weight decay 0.01, batch 32",
        "evidence_status": "paper-verified",
        "evidence_anchor": "flashvsr PDF p4 Fig.2, p5 Eq.2, p6 Sec.4.1",
        "caveat": "This trains the restoration DiT, not the base Wan VAE.",
    },
    {
        "model": "FlashVSR TCDecoder",
        "training_regime": "decoder-only conditional distillation",
        "trainable_parts": "TCDecoder",
        "frozen_parts": "Wan encoder and Wan decoder teacher paths",
        "losses": "MSE+LPIPS to GT plus MSE+LPIPS to Wan decoder output",
        "staging": "trained separately on 61-frame 384x384 clips for about 2 days",
        "optimizer_schedule": "paper reports separate training; exact optimizer details follow implementation context",
        "evidence_status": "paper-verified+code-verified",
        "evidence_anchor": "flashvsr PDF p5 Fig.4/Eq.3 and p6 Sec.4.1; source_code/flashvsr/TCDecoder.py",
        "caveat": "Teacher reconstruction stabilizes detail while direct GT supervision corrects teacher bias.",
    },
]


DATASET_ROWS = [
    {
        "model": "VQGAN / LDM",
        "data_sources": "ImageNet, OpenImages and task-specific image datasets in reported experiments",
        "cleaning_filtering": "dataset-specific",
        "sampling": "random image crops/resizing",
        "input_tensor": "RGB image [B,3,H,W], normalized to model range",
        "target_tensor": "same RGB image for tokenizer pretraining",
        "pair_construction": "self-reconstruction",
        "evidence_status": "paper-verified",
        "evidence_anchor": "vqgan and ldm papers",
        "notes": "Generation datasets and tokenizer datasets need not be identical.",
    },
    {
        "model": "DiT",
        "data_sources": "ImageNet 256/512",
        "cleaning_filtering": "standard ImageNet labels and preprocessing",
        "sampling": "image crop/resize then frozen VAE encoding",
        "input_tensor": "latent x [B,4,H/8,W/8] then p x p patchify",
        "target_tensor": "diffusion noise/variance target in latent space",
        "pair_construction": "image-label pair; no LQ-HQ pair",
        "evidence_status": "paper-verified",
        "evidence_anchor": "dit PDF p3-5",
        "notes": "Decode is outside the training inner loop.",
    },
    {
        "model": "SD3",
        "data_sources": "large-scale image-text data; ImageNet and CC12M for controlled experiments",
        "cleaning_filtering": "NSFW filtering and SSCD-based exact/semantic deduplication described",
        "sampling": "resolution buckets; image and text embeddings precomputed",
        "input_tensor": "image latent [B,16,H/8,W/8] plus text sequences",
        "target_tensor": "rectified-flow velocity target",
        "pair_construction": "image-caption pair",
        "evidence_status": "paper-verified",
        "evidence_anchor": "sd3 PDF Sec.5, App.E",
        "notes": "Precomputation saves memory/compute because frozen encoders do not change.",
    },
    {
        "model": "TiTok",
        "data_sources": "ImageNet-1K; some compared models use OpenImages/LAION subsets",
        "cleaning_filtering": "standard benchmark preprocessing",
        "sampling": "256x256 or 512x512 image patches",
        "input_tensor": "image patches plus K latent tokens",
        "target_tensor": "stage 1 proxy codes; stage 2 RGB image",
        "pair_construction": "self-reconstruction plus teacher-code targets",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2406.07550 lines 177-190,223-226",
        "notes": "Proxy-code data can be precomputed and cached.",
    },
    {
        "model": "DC-AE",
        "data_sources": "ImageNet and high-resolution adaptation data reported by the paper",
        "cleaning_filtering": "resolution-aware phase construction",
        "sampling": "low-resolution global crops then high-resolution latent/local crops",
        "input_tensor": "RGB [B,3,H,W] at phase-specific resolutions",
        "target_tensor": "same image globally or local high-resolution patches",
        "pair_construction": "self-reconstruction with phase-specific crop scopes",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2410.10733 Sec.3 and training details",
        "notes": "Dataset resolution distribution is part of the method, not a neutral implementation detail.",
    },
    {
        "model": "Open-Sora 1.2 VAE",
        "data_sources": "Pexels and Pixabay videos",
        "cleaning_filtering": "project data pipeline covers quality, motion and caption processing",
        "sampling": "mainly 17-frame 256x256 clips; final stage random lengths up to 34 with zero padding",
        "input_tensor": "video [B,3,T,H,W]",
        "target_tensor": "2D-VAE features early; RGB video late",
        "pair_construction": "self-reconstruction and feature-alignment curriculum",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2412.20404 lines 66 and HTML S3.SS1",
        "notes": "Mixed lengths are introduced only in the late stage.",
    },
    {
        "model": "CogVideoX",
        "data_sources": "large image/video corpus with internally generated dense captions",
        "cleaning_filtering": "multi-stage quality and caption pipeline; high-quality cooling subset",
        "sampling": "mixed-duration batches and Frame Pack",
        "input_tensor": "video [B,3,T,H,W] encoded to causal latent",
        "target_tensor": "reconstruction for VAE; diffusion target for CogVideoX DiT",
        "pair_construction": "self-reconstruction for VAE; video-caption for DiT",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2408.06072 Fig.6-7 and training sections",
        "notes": "Caption density is treated as a model-quality lever.",
    },
    {
        "model": "VidTok",
        "data_sources": "multiple open video datasets under unified evaluation",
        "cleaning_filtering": "common protocol for continuous/discrete variants",
        "sampling": "lower-FPS clips improve motion representation; low-res then high-res stages",
        "input_tensor": "video [B,3,T,H,W]",
        "target_tensor": "same video",
        "pair_construction": "self-reconstruction",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2412.13061 lines 40-60; Fig.6",
        "notes": "Frame rate is a semantic sampling hyperparameter, not only I/O throughput.",
    },
    {
        "model": "Cosmos Tokenizer",
        "data_sources": "large physical-AI image/video corpus",
        "cleaning_filtering": "shot splitting, quality and motion filtering, VLM annotation, semantic deduplication",
        "sampling": "image-video joint training; first frame separately preserved",
        "input_tensor": "image [B,3,H,W] or video [B,3,T,H,W]",
        "target_tensor": "same visual signal or teacher continuous tokens for diffusion decoder",
        "pair_construction": "self-reconstruction; discrete-to-continuous decoder pairing",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2501.03575 tokenizer/data sections and Fig.15",
        "notes": "One tokenizer family serves both continuous diffusion and discrete AR models.",
    },
    {
        "model": "Wan",
        "data_sources": "large internal image and video corpus; image volume reported near 10x video volume for joint training",
        "cleaning_filtering": "quality, motion and category proportions adjusted across stages",
        "sampling": "image-video joint training and staged resolution/duration curriculum",
        "input_tensor": "image or video mapped by Wan VAE to 16-channel causal latent",
        "target_tensor": "VAE reconstruction or DiT flow target",
        "pair_construction": "self-reconstruction for VAE; captioned image/video for DiT",
        "evidence_status": "paper-verified",
        "evidence_anchor": "ar5iv_2503.20314 Fig.3, Wan-VAE section, lines 1151-1154",
        "notes": "Exact base VAE training corpus and loss weights remain undisclosed.",
    },
    {
        "model": "FlashVSR / VSR-120K",
        "data_sources": "Videvo, Pexels and Pixabay; initial 600K clips and 220K images",
        "cleaning_filtering": "LAION-Aesthetic, MUSIQ and RAFT motion filtering",
        "sampling": "final 120K videos, average >350 frames, plus 180K HQ images",
        "input_tensor": "paired LR-HR video; images treated as T=1 video in stage 1",
        "target_tensor": "HR video/image; latent and pixel targets depend on stage",
        "pair_construction": "RealBasicVSR degradation pipeline synthesizes LR from HQ",
        "evidence_status": "paper-verified",
        "evidence_anchor": "flashvsr PDF p3 Sec.3.1 and p6 Sec.4.1",
        "notes": "Stage 1 uses 89-frame 768x1280 clips plus images; TCDecoder uses 61-frame 384x384 clips.",
    },
]


FLASHVSR_ROWS = [
    {
        "module": "LQ_proj_in",
        "category": "conditional projection",
        "input": "LR RGB video [B,3,T,H,W]",
        "operations": "PixelShuffle3d-style spatial rearrangement; causal Conv3d stack; RMSNorm/SiLU; projection to DiT feature space",
        "output": "LQ condition feature aligned with noisy Wan latent",
        "trained_when": "stage 1; converted/adapted to causal form in stage 2",
        "inference_role": "replaces VAE encoder for LR conditioning",
        "loss_supervision": "indirect via flow-matching/restoration objectives",
        "evidence": "flashvsr PDF p4 Sec.3.2; source_code/flashvsr/utils.py:54-95",
        "common_misread": "It is not a complete encoder and does not produce the Wan posterior distribution.",
    },
    {
        "module": "Wan Encoder",
        "category": "full causal VAE encoder",
        "input": "HR video [B,3,T,H,W] during VAE/teacher paths",
        "operations": "causal 3D residual hierarchy; temporal x4 and spatial x8 compression; Gaussian posterior",
        "output": "16-channel Wan latent",
        "trained_when": "pretrained before FlashVSR",
        "inference_role": "not required for LR condition injection in the final FlashVSR path",
        "loss_supervision": "Wan VAE pretraining recipe not fully public",
        "evidence": "Wan Fig.5; source_code/wan/wan/modules/vae.py",
        "common_misread": "Do not equate it with LQ_proj_in.",
    },
    {
        "module": "WanDecoder",
        "category": "full causal VAE decoder",
        "input": "16-channel Wan latent",
        "operations": "full 3D causal ResNet decoder with temporal/spatial upsampling and cache",
        "output": "RGB HR video",
        "trained_when": "pretrained Wan VAE",
        "inference_role": "FlashVSR Full quality path; about 70% of runtime at 768x1408 in paper analysis",
        "loss_supervision": "also serves as a teacher target for TCDecoder",
        "evidence": "flashvsr PDF p5 Sec.3.4; source_code/flashvsr/wan_video_vae.py",
        "common_misread": "This is not the lightweight decoder used by Ours-Tiny.",
    },
    {
        "module": "TCDecoder",
        "category": "tiny causal conditional decoder",
        "input": "predicted Wan latent plus LR RGB conditional features",
        "operations": "compact convolutional decoder; PixelShuffle3d(4,8,8); LR-conditioned reconstruction",
        "output": "RGB HR video",
        "trained_when": "separately after restoration model; 61-frame 384x384 clips",
        "inference_role": "Ours-Tiny path; nearly 7x decoder speedup in paper",
        "loss_supervision": "MSE+LPIPS to GT and MSE+LPIPS to WanDecoder output",
        "evidence": "flashvsr PDF p5 Fig.4/Eq.3; source_code/flashvsr/TCDecoder.py:73-213",
        "common_misread": "It is decoder-only and must not be called a VAE or tokenizer.",
    },
]


TERMINOLOGY_ROWS = [
    {"term_en": "Encoder", "term_zh": "编码器", "definition": "Maps pixels or video frames into a latent representation.", "pitfall": "A condition projector may resemble an encoder but need not model a posterior."},
    {"term_en": "Decoder", "term_zh": "解码器", "definition": "Maps latent representations back to pixels or frames.", "pitfall": "A denoising decoder may also perform a diffusion step, as in LTX-Video."},
    {"term_en": "Tokenizer", "term_zh": "视觉分词器", "definition": "An encoder-bottleneck-decoder system defining the tokens consumed by a generative model.", "pitfall": "Tokens may be continuous tensors or discrete indices."},
    {"term_en": "VAE", "term_zh": "变分自编码器", "definition": "A probabilistic autoencoder with a regularized latent distribution.", "pitfall": "Modern 'VAE' implementations may use perceptual and adversarial objectives beyond the original ELBO."},
    {"term_en": "VQ", "term_zh": "向量量化", "definition": "Maps continuous encoder outputs to discrete codebook entries.", "pitfall": "Codebook collapse and inactive entries can reduce effective capacity."},
    {"term_en": "Latent channel", "term_zh": "潜变量通道", "definition": "Feature dimension at each latent spatial-temporal position.", "pitfall": "More channels improve reconstruction but make the DiT prediction problem harder."},
    {"term_en": "Spatial compression factor", "term_zh": "空间压缩倍率", "definition": "Ratio from H,W pixels to latent H/f,W/f.", "pitfall": "It is distinct from DiT patch size and from total token compression."},
    {"term_en": "Temporal causality", "term_zh": "时间因果性", "definition": "Output at time t does not depend on future frames.", "pitfall": "A nominal causal convolution can still break streaming if normalization or padding uses future context."},
    {"term_en": "Perceptual loss", "term_zh": "感知损失", "definition": "Feature-space distance, commonly LPIPS, used to preserve perceptual detail.", "pitfall": "It can trade pixel fidelity for plausible texture and must be balanced with reconstruction losses."},
    {"term_en": "Adversarial loss", "term_zh": "对抗损失", "definition": "Discriminator-based objective encouraging realistic local statistics.", "pitfall": "Starting too early or weighting too highly can destabilize reconstruction."},
    {"term_en": "Frozen latent training", "term_zh": "冻结潜空间训练", "definition": "Precompute or freeze tokenizer outputs while training the DiT.", "pitfall": "No gradient improves decoder defects; tokenizer quality is a hard ceiling."},
    {"term_en": "Conditional decoder", "term_zh": "条件解码器", "definition": "Decoder that consumes latent plus an auxiliary observation such as LR frames.", "pitfall": "It can recover details from the observation but may over-copy degradations without robust training pairs."},
]


def write_csv(name, rows):
    path = ROOT / "metadata" / name
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8-sig", newline="") as stream:
        writer = csv.DictWriter(stream, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)
    return path


def main():
    paths = [
        write_csv("architecture_matrix.csv", ARCHITECTURE_ROWS),
        write_csv("training_matrix.csv", TRAINING_ROWS),
        write_csv("dataset_matrix.csv", DATASET_ROWS),
        write_csv("flashvsr_modules.csv", FLASHVSR_ROWS),
        write_csv("terminology.csv", TERMINOLOGY_ROWS),
    ]
    summary = {
        "architecture_rows": len(ARCHITECTURE_ROWS),
        "training_rows": len(TRAINING_ROWS),
        "dataset_rows": len(DATASET_ROWS),
        "flashvsr_rows": len(FLASHVSR_ROWS),
        "terminology_rows": len(TERMINOLOGY_ROWS),
        "files": [str(path) for path in paths],
    }
    (ROOT / "metadata" / "evidence_matrix_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8"
    )
    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()
